In [6]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

# Splitting our dataset into train and test set

In [3]:
df = pd.read_pickle("data/clean_dataset.pkl")

In [5]:
df.shape

(7043, 21)

In [9]:
len(train_test_split(df, test_size=.2, random_state=17))

2

In [28]:
train, test = train_test_split(df, test_size=.2, random_state=17)

In [31]:
train = train.reset_index(drop=True)
test = test.reset_index(drop=True)

In [32]:
train.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,9369-XFEHK,Female,1,Yes,No,33,Yes,1,Fiber optic,0,...,0,0,0,0,Month-to-month,Yes,Bank transfer (automatic),80.60,2656.50,Yes
1,3545-CNWRG,Female,0,Yes,Yes,49,Yes,1,Fiber optic,0,...,0,0,1,1,Month-to-month,Yes,Electronic check,98.35,4889.20,No
2,0899-WZRSD,Male,0,No,No,56,Yes,1,Fiber optic,1,...,0,1,1,1,Month-to-month,Yes,Mailed check,105.35,5794.45,No
3,1764-VUUMT,Male,0,No,Yes,66,Yes,0,No,0,...,0,0,0,0,Two year,No,Credit card (automatic),19.95,1269.10,No
4,2903-YYTBW,Male,0,Yes,Yes,1,Yes,0,DSL,0,...,0,0,0,0,Month-to-month,No,Electronic check,44.55,44.55,No

In [33]:
test.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,8707-RMEZH,Female,1,Yes,No,69,Yes,0,Fiber optic,1,...,0,0,0,1,One year,No,Credit card (automatic),87.30,6055.55,No
1,1216-BGTSP,Male,0,No,No,45,Yes,1,Fiber optic,1,...,1,1,1,1,Month-to-month,Yes,Credit card (automatic),108.45,4964.70,No
2,5118-MUEYH,Female,0,Yes,No,48,Yes,1,Fiber optic,0,...,0,1,1,1,Month-to-month,Yes,Credit card (automatic),105.10,5083.55,No
3,4821-SJHJV,Female,0,Yes,Yes,32,Yes,1,Fiber optic,1,...,0,0,1,0,Month-to-month,No,Electronic check,89.60,2901.80,No
4,8245-UMPYT,Female,1,No,No,16,Yes,1,Fiber optic,0,...,0,0,1,1,Month-to-month,Yes,Electronic check,96.40,1581.20,Yes

In [34]:
train.to_pickle("data/train.pkl")
test.to_pickle("data/test.pkl")