In [24]:
import pandas as pd
import numpy as np

pd.set_option('display.max_columns', 84)
pd.set_option('display.max_rows', 84)

In [3]:
df = pd.read_csv("data/vehicles_messy.csv", low_memory=False)

In [7]:
df.head()

,barrels08,barrelsA08,charge120,charge240,city08,city08U,cityA08,cityA08U,cityCD,cityE,cityUF,co2,co2A,co2TailpipeAGpm,co2TailpipeGpm,comb08,comb08U,combA08,combA08U,combE,combinedCD,combinedUF,cylinders,displ,drive,engId,eng_dscr,feScore,fuelCost08,fuelCostA08,fuelType,fuelType1,ghgScore,ghgScoreA,highway08,highway08U,highwayA08,highwayA08U,highwayCD,highwayE,highwayUF,hlv,hpv,id,lv2,lv4,make,model,mpgData,phevBlended,pv2,pv4,range,rangeCity,rangeCityA,rangeHwy,rangeHwyA,trany,UCity,UCityA,UHighway,UHighwayA,VClass,year,youSaveSpend,guzzler,trans_dscr,tCharger,sCharger,atvType,fuelType2,rangeA,evMotor,mfrCode,c240Dscr,charge240b,c240bDscr,createdOn,modifiedOn,startStop,phevCity,phevHwy,phevComb
0,15.695714,0.0,0.0,0.0,19,0.0,0,0.0,0.0,0.0,0.0,-1,-1,0.0,423.190476,21,0.0,0,0.0,0.0,0.0,0.0,4.0,2.0,Rear-Wheel Drive,9011,(FFS),-1,1600,0,Regular,Regular Gasoline,-1,-1,25,0.0,0,0.0,0.0,0.0,0.0,0,0,1,0,0,Alfa Romeo,Spider Veloce 2000,Y,False,0,0,0,0.0,0.0,0.0,0.0,Manual 5-spd,23.3333,0.0,35.0000,0.0,Two Seaters,1985,-1250,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,NaN,0,0,0
1,29.964545,0.0,0.0,0.0,9,0.0,0,0.0,0.0,0.0,0.0,-1,-1,0.0,807.909091,11,0.0,0,0.0,0.0,0.0,0.0,12.0,4.9,Rear-Wheel Drive,22020,(GUZZLER),-1,3050,0,Regular,Regular Gasoline,-1,-1,14,0.0,0,0.0,0.0,0.0,0.0,0,0,10,0,0,Ferrari,Testarossa,N,False,0,0,0,0.0,0.0,0.0,0.0,Manual 5-spd,11.0000,0.0,19.0000,0.0,Two Seaters,1985,-8500,T,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,NaN,0,0,0
2,12.207778,0.0,0.0,0.0,23,0.0,0,0.0,0.0,0.0,0.0,-1,-1,0.0,329.148148,27,0.0,0,0.0,0.0,0.0,0.0,4.0,2.2,Front-Wheel Drive,2100,(FFS),-1,1250,0,Regular,Regular Gasoline,-1,-1,33,0.0,0,0.0,0.0,0.0,0.0,19,77,100,0,0,Dodge,Charger,Y,False,0,0,0,0.0,0.0,0.0,0.0,Manual 5-spd,29.0000,0.0,47.0000,0.0,Subcompact Cars,1985,500,NaN,SIL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,NaN,0,0,0
3,29.964545,0.0,0.0,0.0,10,0.0,0,0.0,0.0,0.0,0.0,-1,-1,0.0,807.909091,11,0.0,0,0.0,0.0,0.0,0.0,8.0,5.2,Rear-Wheel Drive,2850,NaN,-1,3050,0,Regular,Regular Gasoline,-1,-1,12,0.0,0,0.0,0.0,0.0,0.0,0,0,1000,0,0,Dodge,B150/B250 Wagon 2WD,N,False,0,0,0,0.0,0.0,0.0,0.0,Automatic 3-spd,12.2222,0.0,16.6667,0.0,Vans,1985,-8500,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,NaN,0,0,0
4,17.347895,0.0,0.0,0.0,17,0.0,0,0.0,0.0,0.0,0.0,-1,-1,0.0,467.736842,19,0.0,0,0.0,0.0,0.0,0.0,4.0,2.2,4-Wheel or All-Wheel Drive,66031,"(FFS,TRBO)",-1,2150,0,Premium,Premium Gasoline,-1,-1,23,0.0,0,0.0,0.0,0.0,0.0,0,0,10000,0,14,Subaru,Legacy AWD Turbo,N,False,0,90,0,0.0,0.0,0.0,0.0,Manual 5-spd,21.0000,0.0,32.0000,0.0,Compact Cars,1993,-4000,NaN,NaN,T,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,NaN,0,0,0

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 37843 entries, 0 to 37842
Data columns (total 83 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   barrels08        37843 non-null  float64
 1   barrelsA08       37843 non-null  float64
 2   charge120        37843 non-null  float64
 3   charge240        37843 non-null  float64
 4   city08           37843 non-null  int64
 5   city08U          37843 non-null  float64
 6   cityA08          37843 non-null  int64
 7   cityA08U         37843 non-null  float64
 8   cityCD           37843 non-null  float64
 9   cityE            37843 non-null  float64
 10  cityUF           37843 non-null  float64
 11  co2              37843 non-null  int64
 12  co2A             37843 non-null  int64
 13  co2TailpipeAGpm  37843 non-null  float64
 14  co2TailpipeGpm   37843 non-null  float64
 15  comb08           37843 non-null  int64
 16  comb08U          37843 non-null  float64
 17  combA08          37843 non-null  int64
 18  combA08U         37843 non-null  float64
 19  combE            37843 non-null  float64
 20  combinedCD       37843 non-null  float64
 21  combinedUF       37843 non-null  float64
 22  cylinders        37720 non-null  float64
 23  displ            37723 non-null  float64
 24  drive            36654 non-null  object
 25  engId            37843 non-null  int64
 26  eng_dscr         22440 non-null  object
 27  feScore          37843 non-null  int64
 28  fuelCost08       37843 non-null  int64
 29  fuelCostA08      37843 non-null  int64
 30  fuelType         37843 non-null  object
 31  fuelType1        37843 non-null  object
 32  ghgScore         37843 non-null  int64
 33  ghgScoreA        37843 non-null  int64
 34  highway08        37843 non-null  int64
 35  highway08U       37843 non-null  float64
 36  highwayA08       37843 non-null  int64
 37  highwayA08U      37843 non-null  float64
 38  highwayCD        37843 non-null  float64
 39  highwayE         37843 non-null  float64
 40  highwayUF        37843 non-null  float64
 41  hlv              37843 non-null  int64
 42  hpv              37843 non-null  int64
 43  id               37843 non-null  int64
 44  lv2              37843 non-null  int64
 45  lv4              37843 non-null  int64
 46  make             37843 non-null  object
 47  model            37843 non-null  object
 48  mpgData          37843 non-null  object
 49  phevBlended      37843 non-null  bool
 50  pv2              37843 non-null  int64
 51  pv4              37843 non-null  int64
 52  range            37843 non-null  int64
 53  rangeCity        37843 non-null  float64
 54  rangeCityA       37843 non-null  float64
 55  rangeHwy         37843 non-null  float64
 56  rangeHwyA        37843 non-null  float64
 57  trany            37832 non-null  object
 58  UCity            37843 non-null  float64
 59  UCityA           37843 non-null  float64
 60  UHighway         37843 non-null  float64
 61  UHighwayA        37843 non-null  float64
 62  VClass           37843 non-null  object
 63  year             37843 non-null  int64
 64  youSaveSpend     37843 non-null  int64
 65  guzzler          2281 non-null   object
 66  trans_dscr       15047 non-null  object
 67  tCharger         5186 non-null   object
 68  sCharger         666 non-null    object
 69  atvType          3072 non-null   object
 70  fuelType2        1408 non-null   object
 71  rangeA           1403 non-null   object
 72  evMotor          562 non-null    object
 73  mfrCode          7025 non-null   object
 74  c240Dscr         37 non-null     object
 75  charge240b       37843 non-null  float64
 76  c240bDscr        36 non-null     object
 77  createdOn        37843 non-null  object
 78  modifiedOn       37843 non-null  object
 79  startStop        6138 non-null   object
 80  phevCity         37843 non-null  int64
 81  phevHwy          37843 non-null  int64
 82  phevComb         37843 non-null  int64
dtypes: bool(1), float64(32), int64(27), object(23)
memory usage: 23.7+ MB

In [11]:
df.describe()

,barrels08,barrelsA08,charge120,charge240,city08,city08U,cityA08,cityA08U,cityCD,cityE,cityUF,co2,co2A,co2TailpipeAGpm,co2TailpipeGpm,comb08,comb08U,combA08,combA08U,combE,combinedCD,combinedUF,cylinders,displ,engId,feScore,fuelCost08,fuelCostA08,ghgScore,ghgScoreA,highway08,highway08U,highwayA08,highwayA08U,highwayCD,highwayE,highwayUF,hlv,hpv,id,lv2,lv4,pv2,pv4,range,rangeCity,rangeCityA,rangeHwy,rangeHwyA,UCity,UCityA,UHighway,UHighwayA,year,youSaveSpend,charge240b,phevCity,phevHwy,phevComb
count,37843.000000,37843.000000,37843.0,37843.000000,37843.000000,37843.000000,37843.000000,37843.000000,37843.000000,37843.000000,37843.000000,37843.000000,37843.000000,37843.000000,37843.000000,37843.000000,37843.000000,37843.000000,37843.000000,37843.000000,37843.000000,37843.000000,37720.000000,37723.000000,37843.000000,37843.000000,37843.000000,37843.000000,37843.000000,37843.000000,37843.000000,37843.000000,37843.000000,37843.000000,37843.000000,37843.000000,37843.000000,37843.000000,37843.000000,37843.000000,37843.000000,37843.000000,37843.000000,37843.000000,37843.000000,37843.000000,37843.00000,37843.000000,37843.000000,37843.000000,37843.000000,37843.000000,37843.000000,37843.000000,37843.000000,37843.000000,37843.000000,37843.000000,37843.000000
mean,17.532506,0.216169,0.0,0.023531,17.941389,4.042737,0.520149,0.327163,0.000406,0.184790,0.000706,61.503713,5.349919,17.771433,473.179736,20.195809,4.549751,0.581191,0.359027,0.190575,0.000335,0.000691,5.737990,3.318180,8860.308961,-0.035145,1882.060090,79.070105,-0.037206,-0.929630,24.104881,5.438467,0.686891,0.418698,0.000233,0.198247,0.000673,2.026214,10.424332,19019.286235,1.849219,6.165658,13.696113,33.769125,0.392675,0.352618,0.03680,0.343399,0.033475,22.587229,0.652380,33.619221,0.933845,2000.064398,-2658.999022,0.004360,0.069313,0.068203,0.068573
std,4.575950,1.141527,0.0,0.427647,6.660360,9.645820,3.837874,3.542596,0.039918,2.904558,0.019458,153.387715,55.539497,94.129283,122.188847,6.623444,10.389994,3.966255,3.589260,2.979567,0.035284,0.019049,1.751795,1.361399,17829.683477,2.379584,510.280408,417.668580,2.374338,0.627565,6.963192,11.936327,4.308934,3.808877,0.029564,3.091862,0.018583,5.947989,28.148770,11034.784855,4.429983,9.743297,31.269930,45.914462,8.251191,8.049082,1.15827,8.171939,1.032642,9.350163,5.284547,10.048326,6.059456,10.390588,2553.098329,0.142776,1.966806,1.871986,1.913647
min,0.060000,0.000000,0.0,0.000000,6.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-1.000000,-1.000000,0.000000,0.000000,7.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2.000000,0.000000,0.000000,-1.000000,550.000000,0.000000,-1.000000,-1.000000,9.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1984.000000,-22250.000000,0.000000,0.000000,0.000000,0.000000
25%,14.330870,0.000000,0.0,0.000000,15.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-1.000000,-1.000000,0.000000,388.000000,17.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,4.000000,2.200000,0.000000,-1.000000,1500.000000,0.000000,-1.000000,-1.000000,20.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,9461.500000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,18.000000,0.000000,27.100000,0.000000,1990.000000,-4250.000000,0.000000,0.000000,0.000000,0.000000
50%,17.347895,0.000000,0.0,0.000000,17.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-1.000000,-1.000000,0.000000,467.736842,19.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,6.000000,3.000000,211.000000,-1.000000,1850.000000,0.000000,-1.000000,-1.000000,24.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,18923.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,21.000000,0.000000,33.000000,0.000000,2001.000000,-2500.000000,0.000000,0.000000,0.000000,0.000000
75%,20.600625,0.000000,0.0,0.000000,20.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-1.000000,-1.000000,0.000000,555.437500,23.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,6.000000,4.300000,4505.000000,-1.000000,2200.000000,0.000000,-1.000000,-1.000000,27.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,28570.500000,0.000000,13.000000,0.000000,91.000000,0.000000,0.000000,0.00000,0.000000,0.000000,25.139300,0.000000,38.109600,0.000000,2009.000000,-750.000000,0.000000,0.000000,0.000000,0.000000
max,47.087143,18.311667,0.0,12.000000,138.000000,138.304000,127.000000,127.093000,5.350000,122.000000,0.849000,847.000000,719.000000,719.000000,1269.571429,124.000000,124.360100,117.000000,116.936400,121.000000,4.800000,0.834000,16.000000,8.400000,69102.000000,10.000000,5800.000000,3800.000000,10.000000,8.000000,111.000000,111.370000,107.000000,106.531000,4.060000,120.000000,0.813000,49.000000,195.000000,38173.000000,41.000000,55.000000,194.000000,192.000000,315.000000,305.900000,77.50400,346.900000,65.632000,197.577100,181.560900,159.100000,152.187800,2017.000000,4000.000000,7.000000,97.000000,79.000000,88.000000

# 1. Missing Values

In [16]:
df.loc[~df["c240Dscr"].isnull(), "c240Dscr"]

25683      single charger
25684      single charger
25895      3.6 kW charger
25955      single charger
27142      3.6 kW charger
27226    standard charger
27227    standard charger
27384      3.6 kW charger
28560    standard charger
28575    standard charger
28591    standard charger
28592    standard charger
28600    standard charger
28720    standard charger
29443    standard charger
29444    standard charger
29497      7.2 kW charger
29652    standard charger
29654    standard charger
29750      3.6 kW charger
29751      6.6 kW charger
29933    standard charger
29934    standard charger
29935    standard charger
29936    standard charger
29938    standard charger
29939    standard charger
29941    standard charger
29942    standard charger
29943    standard charger
30141    standard charger
30142    standard charger
30143    standard charger
30972    standard charger
30973    standard charger
30974    standard charger
30975    standard charger
Name: c240Dscr, dtype: object

In [25]:
df.isna().sum()

barrels08              0
barrelsA08             0
charge120              0
charge240              0
city08                 0
city08U                0
cityA08                0
cityA08U               0
cityCD                 0
cityE                  0
cityUF                 0
co2                    0
co2A                   0
co2TailpipeAGpm        0
co2TailpipeGpm         0
comb08                 0
comb08U                0
combA08                0
combA08U               0
combE                  0
combinedCD             0
combinedUF             0
cylinders            123
displ                120
drive               1189
engId                  0
eng_dscr           15403
feScore                0
fuelCost08             0
fuelCostA08            0
fuelType               0
fuelType1              0
ghgScore               0
ghgScoreA              0
highway08              0
highway08U             0
highwayA08             0
highwayA08U            0
highwayCD              0
highwayE               0
highwayUF              0
hlv                    0
hpv                    0
id                     0
lv2                    0
lv4                    0
make                   0
model                  0
mpgData                0
phevBlended            0
pv2                    0
pv4                    0
range                  0
rangeCity              0
rangeCityA             0
rangeHwy               0
rangeHwyA              0
trany                 11
UCity                  0
UCityA                 0
UHighway               0
UHighwayA              0
VClass                 0
year                   0
youSaveSpend           0
guzzler            35562
trans_dscr         22796
tCharger           32657
sCharger           37177
atvType            34771
fuelType2          36435
rangeA             36440
evMotor            37281
mfrCode            30818
c240Dscr           37806
charge240b             0
c240bDscr          37807
createdOn              0
modifiedOn             0
startStop          31705
phevCity               0
phevHwy                0
phevComb               0
dtype: int64

## Prioritize columns with missing values

In [37]:
((df.isna().sum() / 37843) * 100).round(2)

barrels08           0.00
barrelsA08          0.00
charge120           0.00
charge240           0.00
city08              0.00
city08U             0.00
cityA08             0.00
cityA08U            0.00
cityCD              0.00
cityE               0.00
cityUF              0.00
co2                 0.00
co2A                0.00
co2TailpipeAGpm     0.00
co2TailpipeGpm      0.00
comb08              0.00
comb08U             0.00
combA08             0.00
combA08U            0.00
combE               0.00
combinedCD          0.00
combinedUF          0.00
cylinders           0.33
displ               0.32
drive               3.14
engId               0.00
eng_dscr           40.70
feScore             0.00
fuelCost08          0.00
fuelCostA08         0.00
fuelType            0.00
fuelType1           0.00
ghgScore            0.00
ghgScoreA           0.00
highway08           0.00
highway08U          0.00
highwayA08          0.00
highwayA08U         0.00
highwayCD           0.00
highwayE            0.00
highwayUF           0.00
hlv                 0.00
hpv                 0.00
id                  0.00
lv2                 0.00
lv4                 0.00
make                0.00
model               0.00
mpgData             0.00
phevBlended         0.00
pv2                 0.00
pv4                 0.00
range               0.00
rangeCity           0.00
rangeCityA          0.00
rangeHwy            0.00
rangeHwyA           0.00
trany               0.03
UCity               0.00
UCityA              0.00
UHighway            0.00
UHighwayA           0.00
VClass              0.00
year                0.00
youSaveSpend        0.00
guzzler            93.97
trans_dscr         60.24
tCharger           86.30
sCharger           98.24
atvType            91.88
fuelType2          96.28
rangeA             96.29
evMotor            98.51
mfrCode            81.44
c240Dscr           99.90
charge240b          0.00
c240bDscr          99.90
createdOn           0.00
modifiedOn          0.00
startStop          83.78
phevCity            0.00
phevHwy             0.00
phevComb            0.00
dtype: float64

In [38]:
len(df)

37843

In [39]:
((df.isna().sum() / len(df)) * 100).round(2)

barrels08           0.00
barrelsA08          0.00
charge120           0.00
charge240           0.00
city08              0.00
city08U             0.00
cityA08             0.00
cityA08U            0.00
cityCD              0.00
cityE               0.00
cityUF              0.00
co2                 0.00
co2A                0.00
co2TailpipeAGpm     0.00
co2TailpipeGpm      0.00
comb08              0.00
comb08U             0.00
combA08             0.00
combA08U            0.00
combE               0.00
combinedCD          0.00
combinedUF          0.00
cylinders           0.33
displ               0.32
drive               3.14
engId               0.00
eng_dscr           40.70
feScore             0.00
fuelCost08          0.00
fuelCostA08         0.00
fuelType            0.00
fuelType1           0.00
ghgScore            0.00
ghgScoreA           0.00
highway08           0.00
highway08U          0.00
highwayA08          0.00
highwayA08U         0.00
highwayCD           0.00
highwayE            0.00
highwayUF           0.00
hlv                 0.00
hpv                 0.00
id                  0.00
lv2                 0.00
lv4                 0.00
make                0.00
model               0.00
mpgData             0.00
phevBlended         0.00
pv2                 0.00
pv4                 0.00
range               0.00
rangeCity           0.00
rangeCityA          0.00
rangeHwy            0.00
rangeHwyA           0.00
trany               0.03
UCity               0.00
UCityA              0.00
UHighway            0.00
UHighwayA           0.00
VClass              0.00
year                0.00
youSaveSpend        0.00
guzzler            93.97
trans_dscr         60.24
tCharger           86.30
sCharger           98.24
atvType            91.88
fuelType2          96.28
rangeA             96.29
evMotor            98.51
mfrCode            81.44
c240Dscr           99.90
charge240b          0.00
c240bDscr          99.90
createdOn           0.00
modifiedOn          0.00
startStop          83.78
phevCity            0.00
phevHwy             0.00
phevComb            0.00
dtype: float64

In [40]:
cols_na = ((df.isna().sum() / len(df)) * 100).round(2)

In [42]:
type(cols_na)

pandas.core.series.Series

In [43]:
cols_na[cols_na > 50]

guzzler       93.97
trans_dscr    60.24
tCharger      86.30
sCharger      98.24
atvType       91.88
fuelType2     96.28
rangeA        96.29
evMotor       98.51
mfrCode       81.44
c240Dscr      99.90
c240bDscr     99.90
startStop     83.78
dtype: float64

Why don't we drop columns with more than 50% missing values

```python
df.drop(columns=[columns])
```

In [45]:
to_drop_series = cols_na[cols_na > 50]

In [49]:
to_drop_series.index

Index(['guzzler', 'trans_dscr', 'tCharger', 'sCharger', 'atvType', 'fuelType2',
       'rangeA', 'evMotor', 'mfrCode', 'c240Dscr', 'c240bDscr', 'startStop'],
      dtype='object')

In [51]:
df = df.drop(columns=to_drop_series.index)

In [68]:
# df.drop(columns=((df
#                   .isna()
#                   .sum() / len(df))
#                  .round(2)
#                  [(df
#                    .isna()
#                    .sum() / len(df))
#                   .round(2) > .3]
#                  .index))

Index(['eng_dscr'], dtype='object')

### Handle missing values for columns `cylinders`

In [70]:
df.isna().sum()

barrels08              0
barrelsA08             0
charge120              0
charge240              0
city08                 0
city08U                0
cityA08                0
cityA08U               0
cityCD                 0
cityE                  0
cityUF                 0
co2                    0
co2A                   0
co2TailpipeAGpm        0
co2TailpipeGpm         0
comb08                 0
comb08U                0
combA08                0
combA08U               0
combE                  0
combinedCD             0
combinedUF             0
cylinders            123
displ                120
drive               1189
engId                  0
eng_dscr           15403
feScore                0
fuelCost08             0
fuelCostA08            0
fuelType               0
fuelType1              0
ghgScore               0
ghgScoreA              0
highway08              0
highway08U             0
highwayA08             0
highwayA08U            0
highwayCD              0
highwayE               0
highwayUF              0
hlv                    0
hpv                    0
id                     0
lv2                    0
lv4                    0
make                   0
model                  0
mpgData                0
phevBlended            0
pv2                    0
pv4                    0
range                  0
rangeCity              0
rangeCityA             0
rangeHwy               0
rangeHwyA              0
trany                 11
UCity                  0
UCityA                 0
UHighway               0
UHighwayA              0
VClass                 0
year                   0
youSaveSpend           0
charge240b             0
createdOn              0
modifiedOn             0
phevCity               0
phevHwy                0
phevComb               0
dtype: int64

In [73]:
df[df["cylinders"].isna()]

,barrels08,barrelsA08,charge120,charge240,city08,city08U,cityA08,cityA08U,cityCD,cityE,cityUF,co2,co2A,co2TailpipeAGpm,co2TailpipeGpm,comb08,comb08U,combA08,combA08U,combE,combinedCD,combinedUF,cylinders,displ,drive,engId,eng_dscr,feScore,fuelCost08,fuelCostA08,fuelType,fuelType1,ghgScore,ghgScoreA,highway08,highway08U,highwayA08,highwayA08U,highwayCD,highwayE,highwayUF,hlv,hpv,id,lv2,lv4,make,model,mpgData,phevBlended,pv2,pv4,range,rangeCity,rangeCityA,rangeHwy,rangeHwyA,trany,UCity,UCityA,UHighway,UHighwayA,VClass,year,youSaveSpend,charge240b,createdOn,modifiedOn,phevCity,phevHwy,phevComb
7138,0.240,0.0,0.0,0.0,81,0.0000,0,0.0,0.0,41.0000,0.0,0,-1,0.0,0.0,85,0.0000,0,0.0,40.0000,0.0,0.0,NaN,NaN,NaN,0,NaN,-1,800,0,Electricity,Electricity,-1,-1,91,0.0000,0,0.0,0.0,37.0000,0.0,0,0,16423,0,0,Nissan,Altra EV,N,False,0,0,90,0.0,0.0,0.0,0.0,NaN,116.2069,0.0,129.6154,0.0,Midsize Station Wagons,2000,2750,0.00,Tue Jan 01 00:00:00 EST 2013,Thu Jul 07 00:00:00 EDT 2016,0,0,0
7139,0.282,0.0,0.0,0.0,81,0.0000,0,0.0,0.0,41.0000,0.0,0,-1,0.0,0.0,72,0.0000,0,0.0,47.0000,0.0,0.0,NaN,NaN,2-Wheel Drive,0,NaN,-1,900,0,Electricity,Electricity,-1,-1,64,0.0000,0,0.0,0.0,53.0000,0.0,0,0,16424,0,0,Toyota,RAV4 EV,N,False,0,0,88,0.0,0.0,0.0,0.0,NaN,116.2069,0.0,91.0811,0.0,Sport Utility Vehicle - 2WD,2000,2250,0.00,Tue Jan 01 00:00:00 EST 2013,Thu Jul 07 00:00:00 EDT 2016,0,0,0
8143,0.282,0.0,0.0,0.0,81,0.0000,0,0.0,0.0,41.0000,0.0,0,-1,0.0,0.0,72,0.0000,0,0.0,47.0000,0.0,0.0,NaN,NaN,2-Wheel Drive,0,NaN,-1,900,0,Electricity,Electricity,-1,-1,64,0.0000,0,0.0,0.0,53.0000,0.0,0,0,17328,0,0,Toyota,RAV4 EV,N,False,0,0,88,0.0,0.0,0.0,0.0,NaN,116.2069,0.0,91.0811,0.0,Sport Utility Vehicle - 2WD,2001,2250,0.00,Tue Jan 01 00:00:00 EST 2013,Thu Jul 07 00:00:00 EDT 2016,0,0,0
8144,0.312,0.0,0.0,0.0,74,0.0000,0,0.0,0.0,46.0000,0.0,0,-1,0.0,0.0,65,0.0000,0,0.0,52.0000,0.0,0.0,NaN,NaN,NaN,0,NaN,-1,1000,0,Electricity,Electricity,-1,-1,58,0.0000,0,0.0,0.0,59.0000,0.0,0,0,17329,0,0,Ford,Th!nk,N,False,0,0,29,0.0,0.0,0.0,0.0,NaN,105.3125,0.0,82.1951,0.0,Two Seaters,2001,1750,0.00,Tue Jan 01 00:00:00 EST 2013,Thu Jul 07 00:00:00 EDT 2016,0,0,0
8146,0.522,0.0,0.0,0.0,45,0.0000,0,0.0,0.0,75.0000,0.0,0,-1,0.0,0.0,39,0.0000,0,0.0,87.0000,0.0,0.0,NaN,NaN,2-Wheel Drive,0,NaN,-1,1700,0,Electricity,Electricity,-1,-1,33,0.0000,0,0.0,0.0,102.0000,0.0,0,0,17330,0,0,Ford,Explorer USPS Electric,N,False,0,0,38,0.0,0.0,0.0,0.0,NaN,62.4074,0.0,46.8056,0.0,Sport Utility Vehicle - 2WD,2001,-1750,0.00,Tue Jan 01 00:00:00 EST 2013,Thu Jul 07 00:00:00 EDT 2016,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30969,0.192,0.0,0.0,4.0,120,119.6000,0,0.0,0.0,28.1744,0.0,0,-1,0.0,0.0,105,105.3754,0,0.0,31.9856,0.0,0.0,NaN,NaN,Front-Wheel Drive,37,NaN,10,600,0,Electricity,Electricity,10,-1,92,92.0000,0,0.0,0.0,36.6438,0.0,0,0,38168,0,19,Kia,Soul Electric,N,False,0,97,93,148.0,0.0,113.8,0.0,Automatic (A1),170.9000,0.0,131.4000,0.0,Small Station Wagons,2017,3750,0.00,Tue Sep 13 00:00:00 EDT 2016,Tue Sep 13 00:00:00 EDT 2016,0,0,0
30972,0.204,0.0,0.0,10.0,98,97.5636,0,0.0,0.0,35.0000,0.0,0,-1,0.0,0.0,99,99.0945,0,0.0,34.0000,0.0,0.0,NaN,NaN,Rear-Wheel Drive,2,NaN,10,650,0,Electricity,Electricity,10,-1,101,101.0322,0,0.0,0.0,33.0000,0.0,26,94,38170,0,0,Tesla,Model S (60 kW-hr battery pack),N,False,0,0,210,207.5,0.0,214.8,0.0,Automatic (A1),132.2000,0.0,136.9000,0.0,Large Cars,2016,3500,3.75,Tue Sep 13 00:00:00 EDT 2016,Tue Sep 13 00:00:00 EDT 2016,0,0,0
30973,0.192,0.0,0.0,12.0,101,101.4750,0,0.0,0.0,33.0000,0.0,0,-1,0.0,0.0,104,103.7678,0,0.0,32.0000,0.0,0.0,NaN,NaN,All-Wheel Drive,21,NaN,10,600,0,Electricity,Electricity,10,-1,107,106.7148,0,0.0,0.0,32.0000,0.0,26,94,38171,0,0,Tesla,Model S AWD - 60D,N,False,0,0,218,221.1,0.0,226.9,0.0,Automatic (A1),137.5000,0.0,144.6000,0.0,Large Cars,2016,3750,3.75,Tue Sep 13 00:00:00 EDT 2016,Tue Sep 13 00:00:00 EDT 2016,0,0,0
30974,0.210,0.0,0.0,12.0,92,92.4713,0,0.0,0.0,36.0000,0.0,0,-1,0.0,0.0,98,97.5232,0,0.0,35.0000,0.0,0.0,NaN,NaN,All-Wheel Drive,15,NaN,10,700,0,Electricity,Electricity,10,-1,105,104.5008,0,0.0,0.0,32.0000,0.0,26,94,38172,0,0,Tesla,Model S AWD - P100D,N,False,0,0,315,305.9,0.0,346.9,0.0,Automatic (A1),125.3000,0.0,141.6000,0.0,Large Cars,2016,3250,4.75,Tue Sep 13 00:00:00 EDT 2016,Tue Sep 13 00:00:00 EDT 2016,0,0,0
30975,0.216,0.0,0.0,12.0,91,91.2362,0,0.0,0.0,37.0000,0.0,0,-1,0.0,0.0,93,92.5663,0,0.0,36.0000,0.0,0.0,NaN,NaN,All-Wheel Drive,12,NaN,10,700,0,Electricity,Electricity,10,-1,94,94.2456,0,0.0,0.0,36.0000,0.0,26,94,38173,0,0,Tesla,Model X AWD - 60D,N,False,0,0,200,196.5,0.0,203.2,0.0,Automatic (A1),124.3000,0.0,128.4000,0.0,Standard Sport Utility Vehicle 4WD,2016,3250,4.75,Tue Sep 13 00:00:00 EDT 2016,Tue Sep 13 00:00:00 EDT 2016,0,0,0

In [74]:
relevant_cols = ["year", "make", "model", "trany", "drive", "fuelType", "cylinders", "displ"]
df.loc[df["cylinders"].isna(), relevant_cols]

,year,make,model,trany,drive,fuelType,cylinders,displ
7138,2000,Nissan,Altra EV,NaN,NaN,Electricity,NaN,NaN
7139,2000,Toyota,RAV4 EV,NaN,2-Wheel Drive,Electricity,NaN,NaN
8143,2001,Toyota,RAV4 EV,NaN,2-Wheel Drive,Electricity,NaN,NaN
8144,2001,Ford,Th!nk,NaN,NaN,Electricity,NaN,NaN
8146,2001,Ford,Explorer USPS Electric,NaN,2-Wheel Drive,Electricity,NaN,NaN
...,...,...,...,...,...,...,...,...
30969,2017,Kia,Soul Electric,Automatic (A1),Front-Wheel Drive,Electricity,NaN,NaN
30972,2016,Tesla,Model S (60 kW-hr battery pack),Automatic (A1),Rear-Wheel Drive,Electricity,NaN,NaN
30973,2016,Tesla,Model S AWD - 60D,Automatic (A1),All-Wheel Drive,Electricity,NaN,NaN
30974,2016,Tesla,Model S AWD - P100D,Automatic (A1),All-Wheel Drive,Electricity,NaN,NaN
30975,2016,Tesla,Model X AWD - 60D,Automatic (A1),All-Wheel Drive,Electricity,NaN,NaN

Impute missing values with 0

In [76]:
df["cylinders"].isna().sum()

123

In [78]:
df["cylinders"].fillna(0).isna().sum()

0

In [80]:
df["cylinders"] = df["cylinders"].fillna(0)

In [81]:
df["displ"] = df["displ"].fillna(0)

In [83]:
df[["cylinders", "displ"]] = df[["cylinders", "displ"]].fillna(0)